import { NextResponse } from "next/server";

export interface LiveChannel {
  id: string;
  name: string;
  category: "News" | "Sports" | "Tech & Space" | "Entertainment" | "Music" | "Nature & Chill" | "Gaming";
  logo: string;
  streamUrl: string;
  embedType: "hls" | "youtube" | "iframe";
  currentShow: string;
  country: string;
  description: string;
}

const CHANNELS: LiveChannel[] = [
  // TECH & SPACE
  {
    id: "nasa-tv",
    name: "NASA TV HD",
    category: "Tech & Space",
    logo: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    embedType: "hls",
    currentShow: "Live Earth Views from ISS & Artemis Mission Prep",
    country: "US",
    description: "Official 24/7 NASA broadcast with views from the International Space Station and live rocket launches.",
  },
  {
    id: "spacex-live",
    name: "SpaceX Starbase Live",
    category: "Tech & Space",
    logo: "https://images.unsplash.com/photo-1517976487504-59a1a04d2037?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/mhJRzQsLZGg?autoplay=1&mute=0",
    embedType: "youtube",
    currentShow: "Starship Flight Test & Megabay Live Cam",
    country: "US",
    description: "24/7 high-definition multi-cam tracking of the Starship orbital launch pad in Boca Chica, Texas.",
  },
  {
    id: "twit-tv",
    name: "TWiT Tech Network",
    category: "Tech & Space",
    logo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://twit.cachefly.net/video/live/twit_live.m3u8",
    embedType: "hls",
    currentShow: "This Week in Tech, AI & Cyber Insights",
    country: "US",
    description: "Leo Laporte and leading tech journalists debate breaking gadgets, AI breakthroughs, and security.",
  },

  // NEWS
  {
    id: "sky-news",
    name: "Sky News International",
    category: "News",
    logo: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/9Auq9mYxFEE?autoplay=1",
    embedType: "youtube",
    currentShow: "Sky World News Live & Breaking Reports",
    country: "UK",
    description: "Global breaking news, political debates, and round-the-clock international correspondent reports.",
  },
  {
    id: "al-jazeera-en",
    name: "Al Jazeera English",
    category: "News",
    logo: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://live-hls-web-aje.getaj.net/AJE/03.m3u8",
    embedType: "hls",
    currentShow: "Newshour Live & Investigative Global Dispatches",
    country: "INT",
    description: "Independent global reporting from the Middle East, Americas, Europe, Africa, and Asia.",
  },
  {
    id: "france24-en",
    name: "France 24 English",
    category: "News",
    logo: "https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://static.france24.com/live/F24_EN_LO_HLS/live_tv.m3u8",
    embedType: "hls",
    currentShow: "European & Global Pulse Live",
    country: "FR",
    description: "Paris-based international news channel providing round-the-clock world events coverage.",
  },
  {
    id: "dw-news",
    name: "DW News (Deutsche Welle)",
    category: "News",
    logo: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    embedType: "hls",
    currentShow: "Journal Live: European Perspectives",
    country: "DE",
    description: "Germany's international public broadcaster featuring unbiased in-depth global journalism.",
  },
  {
    id: "euro-news",
    name: "Euronews English",
    category: "News",
    logo: "https://images.unsplash.com/photo-1498644035638-2c3357894b10?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://euronews-euronews-world-1-us.samsung.wurl.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "Euronews Tonight & World Update",
    country: "EU",
    description: "All views on Europe and world headlines delivered with impartial multilateral journalism.",
  },
  {
    id: "bloomberg-markets",
    name: "Bloomberg Financial",
    category: "News",
    logo: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/dp8PhLsUcFE?autoplay=1",
    embedType: "youtube",
    currentShow: "The Close & Global Markets Today",
    country: "US",
    description: "Real-time stock ticker, macroeconomic analysis, central bank decisions, and Wall Street data.",
  },

  // SPORTS
  {
    id: "redbull-tv",
    name: "Red Bull Extreme Sports",
    category: "Sports",
    logo: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    embedType: "hls",
    currentShow: "Red Bull Rampage Downhill & F1 Highlights",
    country: "AT",
    description: "World championships in downhill mountain biking, extreme motocross, surfing, and air races.",
  },
  {
    id: "fite-mma",
    name: "Combat & MMA Sports",
    category: "Sports",
    logo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://linear-416.frequency.stream/mt/studio/416/hls/master/playlist.m3u8",
    embedType: "hls",
    currentShow: "World Kickboxing Championship & Grappling Live",
    country: "US",
    description: "Live fighting championships, striking events, knockout compilations, and pro wrestling.",
  },
  {
    id: "moto-america",
    name: "MotoAmerica Superbikes",
    category: "Sports",
    logo: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://stream-us.amagi.tv/hls/amagi_hls_data_motoamerica-samsungus/CDN/playlist.m3u8",
    embedType: "hls",
    currentShow: "King of the Baggers & Supersport Grand Prix",
    country: "US",
    description: "Premier road racing motorcycle championship in North America with high-speed 200mph action.",
  },
  {
    id: "world-poker-tour",
    name: "World Poker Tour Live",
    category: "Sports",
    logo: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://wpt-samsung.amagi.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "High Stakes Championship Main Event Final Table",
    country: "US",
    description: "World Poker Tour elite showdowns, all-in hands, and world championship tournament tables.",
  },

  // ENTERTAINMENT & MOVIES
  {
    id: "rakuten-movies",
    name: "Rakuten Action Movies",
    category: "Entertainment",
    logo: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://rakuten-actionmovies-1-eu.rakuten.wurl.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "24/7 Blockbuster Action & Thriller Cinema",
    country: "UK",
    description: "Non-stop Hollywood action, sci-fi, suspense thrillers, and crime cinema streamed around the clock.",
  },
  {
    id: "shout-factory",
    name: "Shout! Factory Cult Classics",
    category: "Entertainment",
    logo: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://shoutfactory-samsungus.amagi.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "Mystery Science Theater 3000 & Cult Sci-Fi",
    country: "US",
    description: "Vintage science fiction, martial arts movies, Mystery Science Theater, and cult comedy legends.",
  },
  {
    id: "anime-all-day",
    name: "RetroCrush Anime TV",
    category: "Entertainment",
    logo: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://retrocrush-samsung.amagi.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "Golden Era Mecha, Shonen & Fantasy Anime",
    country: "JP",
    description: "Dedicated classic anime channel featuring vintage mecha, cyberpunk masterpieces, and beloved series.",
  },
  {
    id: "pluto-comedy",
    name: "Stand-Up Comedy Central",
    category: "Entertainment",
    logo: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://linear-415.frequency.stream/mt/studio/415/hls/master/playlist.m3u8",
    embedType: "hls",
    currentShow: "Live Laughs & Headliner Specials",
    country: "US",
    description: "Hilarious stand-up comedy specials, sketch shows, roast battles, and legendary comics.",
  },

  // GAMING
  {
    id: "ign-tv",
    name: "IGN Live Gaming",
    category: "Gaming",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://ign-samsung.amagi.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "Next-Gen Game Showcases & Walkthroughs",
    country: "US",
    description: "Official IGN stream covering video game reviews, gameplay premieres, developer interviews, and esports.",
  },
  {
    id: "esl-csgo",
    name: "ESL Pro Counter-Strike",
    category: "Gaming",
    logo: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/live_stream?channel=UC0lG2jD_2y5Hovg1Z0Hwz-A",
    embedType: "iframe",
    currentShow: "ESL Pro League Major Playoffs & Clutch Rounds",
    country: "INT",
    description: "Tier-1 CS2 esports tournaments, grand finals, and ace highlights from the world's best teams.",
  },

  // MUSIC
  {
    id: "lofi-girl",
    name: "Lofi Girl 24/7 Radio",
    category: "Music",
    logo: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/jfKfPfyJRdk?autoplay=1",
    embedType: "youtube",
    currentShow: "Beats to Relax / Study to Live Stream",
    country: "FR",
    description: "Iconic 24/7 live chillhop and lofi beats stream for relaxing, coding, studying, and gaming.",
  },
  {
    id: "synthwave-radio",
    name: "Synthwave & Retrowave Radio",
    category: "Music",
    logo: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/4xDzrJKXOOY?autoplay=1",
    embedType: "youtube",
    currentShow: "Neon Dreams & Cyberpunk Darksynth",
    country: "INT",
    description: "80s retro futuristic synthesizers, nostalgic dreamwave, and dark synth cyber beats.",
  },
  {
    id: "stingray-qello",
    name: "Qello Concerts Live",
    category: "Music",
    logo: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://qello-samsung.amagi.tv/playlist.m3u8",
    embedType: "hls",
    currentShow: "Legendary Stadium Concerts & Acoustic Sets",
    country: "US",
    description: "World-famous rock, hip hop, pop, and jazz concerts filmed live in stadiums across the world.",
  },

  // NATURE & CHILL
  {
    id: "monterey-kelp",
    name: "Monterey Bay Kelp Forest",
    category: "Nature & Chill",
    logo: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/2g811Eo7K8U?autoplay=1",
    embedType: "youtube",
    currentShow: "Live Giant Pacific Kelp & Leopard Sharks",
    country: "US",
    description: "Submerged 28-foot tall aquarium tank featuring leopard sharks, wolf eels, and giant kelp.",
  },
  {
    id: "african-wildlife",
    name: "African Wildlife Waterhole",
    category: "Nature & Chill",
    logo: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/O8xmyqVDYTM?autoplay=1",
    embedType: "youtube",
    currentShow: "Kalahari Desert Wild Waterhole Cam",
    country: "ZA",
    description: "Live 24/7 wildlife camera at a natural waterhole in Namibia/Botswana with elephants and lions.",
  },
  {
    id: "coral-reef",
    name: "Tropical Coral Reef Live",
    category: "Nature & Chill",
    logo: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/5ovA7H_b_a8?autoplay=1",
    embedType: "youtube",
    currentShow: "South Pacific Marine Sanctuary HD",
    country: "AU",
    description: "Crystal clear underwater reef camera featuring clownfish, sea turtles, and colorful corals.",
  },
  {
    id: "aurora-cam",
    name: "Northern Lights Aurora Cam",
    category: "Nature & Chill",
    logo: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=300&q=80",
    streamUrl: "https://www.youtube-nocookie.com/embed/v_79P-sYx4E?autoplay=1",
    embedType: "youtube",
    currentShow: "Lapland & Arctic Night Sky Aurora Borealis",
    country: "NO",
    description: "Live night vision sky cameras capturing real-time Aurora Borealis northern lights dance.",
  },
];

export async function GET() {
  return NextResponse.json({
    channels: CHANNELS,
    total: CHANNELS.length,
    categories: [
      "All",
      "News",
      "Sports",
      "Tech & Space",
      "Entertainment",
      "Gaming",
      "Music",
      "Nature & Chill",
    ],
    updatedAt: new Date().toISOString(),
  });
}
